apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azure-identity-binding
spec:
  AzureIdentity: "{{ .Values.azureIdentity }}"
  Selector: "{{ .Values.global.operatorName }}"